server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: LoginService

  datasource:
    url: jdbc:mysql://localhost:3306/login_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: mySecretKey1234567890123456789012
  expiration: 3600000
