spring.application.name=backend

#DB config
spring.datasource.url=jdbc:mysql://localhost:3306/Food_Acc_Management?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=vishwa
spring.datasource.password=manager
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
#default server port 8080
#server.port=9090


#spring.application.name=backend
#
## ================================
## Database config (from ENV)
## ================================
#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USER}
#spring.datasource.password=${DB_PASSWORD}
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#spring.jpa.open-in-view=false
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#
## ================================
## Server
## ================================
#server.port=8080
