apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  type: LoadBalancer # Good for Docker Desktop/Windows; use NodePort for Minikube
  selector:
    app: react-app # Must match the label in deployment.yaml
  ports:
    - protocol: TCP
      port: 80       # External port
      targetPort: 80 # Port on the container
