# ---------- Build Stage ----------
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ARG VITE_SPRING_API
ENV VITE_SPRING_API=$VITE_SPRING_API

ARG VITE_ADMIN_API
ENV VITE_ADMIN_API=$VITE_ADMIN_API

RUN npm run build


# ---------- Production Stage ----------
FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
